version: '3'

services:
  video-analysis-api:
    build: .
    ports:
      - "${EXTERNAL_PORT}:5000"
    volumes:
      - .:/app:ro
    environment:
      - FLASK_DEBUG=0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PYTHONPATH=/app
    restart: unless-stopped
