services:
  video-analysis-api:
    build: .
    volumes:
      - ./:/app
    environment:
      - FLASK_DEBUG=0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "${EXTERNAL_PORT}:5000"
    restart: unless-stopped
