version: '3'

services:
  video-analysis-api:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_DEBUG=0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: unless-stopped
